server:
  port: 8080

spring:
    datasource:
        name: huihan
        url: jdbc:mysql://47.104.12.182:3306/huihan
        username: root
        password: huihan
        driver-class-name: com.mysql.jdbc.Driver

    ybatis:
        mapper-locations: classpath:c
        type-aliases-package: com.example.dao.entity